import type { NextConfig } from "next";
import path from "path";

const nextConfig: NextConfig = {
  outputFileTracingRoot: path.join(__dirname),
  trailingSlash: false,
  reactStrictMode: true,
  images: {
    formats: ["image/avif", "image/webp"],
    remotePatterns: [{ protocol: "https", hostname: "**" }],
  },
  rewrites: async () => [{ source: "/favicon.ico", destination: "/icon" }],
  redirects: async () => [
    { source: "/about", destination: "/sobre", permanent: true },
    { source: "/contact", destination: "/contato", permanent: true },
    { source: "/privacy", destination: "/privacidade", permanent: true },
    { source: "/terms", destination: "/termos", permanent: true },
    { source: "/news", destination: "/noticias", permanent: true },
    { source: "/news/:slug", destination: "/noticias/:slug", permanent: true },
    { source: "/calendar", destination: "/calendario", permanent: true },
    { source: "/results", destination: "/resultados", permanent: true },
    { source: "/nosotros", destination: "/sobre", permanent: true },
    { source: "/contacto", destination: "/contato", permanent: true },
    { source: "/privacidad", destination: "/privacidade", permanent: true },
    { source: "/terminos", destination: "/termos", permanent: true },
    { source: "/nucleos", destination: "/pracas", permanent: true },
    { source: "/nucleos/:slug", destination: "/pracas/:slug", permanent: true },
    { source: "/comunidades", destination: "/pracas", permanent: true },
    { source: "/comunidades/:slug", destination: "/pracas/:slug", permanent: true },
    { source: "/colegios", destination: "/pracas", permanent: true },
    { source: "/colegios/:slug", destination: "/pracas/:slug", permanent: true },
    { source: "/academias", destination: "/pracas", permanent: true },
    { source: "/academias/:slug", destination: "/pracas/:slug", permanent: true },
    { source: "/teams", destination: "/pracas", permanent: true },
    { source: "/teams/:slug", destination: "/pracas/:slug", permanent: true },
    { source: "/houses", destination: "/pracas", permanent: true },
    { source: "/houses/:slug", destination: "/pracas/:slug", permanent: true },
    { source: "/equipes", destination: "/pracas", permanent: true },
    { source: "/equipes/:slug", destination: "/pracas/:slug", permanent: true },
    { source: "/clubes", destination: "/pracas", permanent: true },
    { source: "/clubes/:slug", destination: "/pracas/:slug", permanent: true },
    { source: "/campos", destination: "/pracas", permanent: true },
    { source: "/campos/:slug", destination: "/pracas/:slug", permanent: true },
    { source: "/bancas", destination: "/pracas", permanent: true },
    { source: "/bancas/:slug", destination: "/pracas/:slug", permanent: true },
    { source: "/bancadas", destination: "/pracas", permanent: true },
    { source: "/bancadas/:slug", destination: "/pracas/:slug", permanent: true },
    { source: "/circuitos", destination: "/tardes", permanent: true },
    { source: "/circuitos/:slug", destination: "/tardes", permanent: true },
    { source: "/etapas", destination: "/tardes", permanent: true },
    { source: "/etapas/:slug", destination: "/tardes", permanent: true },
    { source: "/stops", destination: "/tardes", permanent: true },
    { source: "/barrios", destination: "/tardes", permanent: true },
    { source: "/modalidades", destination: "/categorias", permanent: true },
    { source: "/modalidades/:slug", destination: "/categorias/:slug", permanent: true },
    { source: "/disciplinas", destination: "/categorias", permanent: true },
    { source: "/disciplinas/:slug", destination: "/categorias/:slug", permanent: true },
    { source: "/categories", destination: "/categorias", permanent: true },
    { source: "/categories/:slug", destination: "/categorias/:slug", permanent: true },
    { source: "/casas", destination: "/pracas", permanent: true },
    { source: "/casas/:slug", destination: "/pracas/:slug", permanent: true },
    { source: "/paradas", destination: "/tardes", permanent: true },
    { source: "/artigo/:slug", destination: "/noticias/:slug", permanent: true },
    { source: "/noticia/:slug", destination: "/noticias/:slug", permanent: true },
    { source: "/categoria/:slug", destination: "/categorias/:slug", permanent: true },
    { source: "/ultimas", destination: "/noticias", permanent: true },
    { source: "/alertas", destination: "/noticias", permanent: true },
    { source: "/ao-vivo", destination: "/resultados", permanent: true },
    { source: "/ao-vivo/:slug", destination: "/resultados", permanent: true },
    { source: "/futebol", destination: "/", permanent: true },
    { source: "/estados", destination: "/pracas", permanent: true },
    { source: "/estados/:uf", destination: "/pracas", permanent: true },
    { source: "/liga/:slug", destination: "/categorias", permanent: true },
    { source: "/busca", destination: "/", permanent: true },
    { source: "/feed", destination: "/rss.xml", permanent: true },
    { source: "/rss", destination: "/rss.xml", permanent: true },
    { source: "/feed.xml", destination: "/rss.xml", permanent: true },
  ],
  headers: async () => [
    {
      source: "/:path*",
      headers: [
        { key: "X-Content-Type-Options", value: "nosniff" },
        { key: "X-Frame-Options", value: "SAMEORIGIN" },
        { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
        {
          key: "Strict-Transport-Security",
          value: "max-age=63072000; includeSubDomains; preload",
        },
        { key: "Permissions-Policy", value: "camera=(), microphone=(), geolocation=()" },
      ],
    },
    {
      source: "/:file(rss.xml|sitemap.xml|news-sitemap.xml|llms.txt)",
      headers: [{ key: "Access-Control-Allow-Origin", value: "*" }],
    },
  ],
};

export default nextConfig;
