/**
 * Site-specific demo content — generated by SiteAssembler
 * Site: Bola de Domingo
 * DO NOT EDIT MANUALLY
 */

export interface Category {
  id: string;
  name: string;
  slug: string;
  description?: string;
}

export interface Article {
  id: string;
  slug: string;
  title: string;
  excerpt: string;
  content: string;
  category: string;
  categorySlug: string;
  author: string;
  publishedAt: string;
  imageUrl?: string;
  isVideo?: boolean;
  readCount?: number;
  featured?: boolean;
  keyPoints?: string[];
}

export interface BreakingHeadline {
  id: string;
  text: string;
  slug?: string;
  urgent?: boolean;
}

export interface AlertItem {
  id: string;
  level: string;
  title: string;
  href?: string;
  publishedAt: string;
}

export interface LiveUpdate {
  id: string;
  at: string;
  source: string;
  text: string;
}

export interface LiveStory {
  id: string;
  slug: string;
  title: string;
  summary: string;
  updatedAt: string;
  updates: LiveUpdate[];
}

export const categories: Category[] = [
  {
    "id": "cat-brasileirao",
    "name": "Brasileirão",
    "slug": "brasileirao",
    "description": "Cobertura de Brasileirão em Bola de Domingo"
  },
  {
    "id": "cat-copa-do-brasil",
    "name": "Copa do Brasil",
    "slug": "copa-do-brasil",
    "description": "Cobertura de Copa do Brasil em Bola de Domingo"
  },
  {
    "id": "cat-libertadores",
    "name": "Libertadores",
    "slug": "libertadores",
    "description": "Cobertura de Libertadores em Bola de Domingo"
  },
  {
    "id": "cat-selecao",
    "name": "Seleção",
    "slug": "selecao",
    "description": "Cobertura de Seleção em Bola de Domingo"
  },
  {
    "id": "cat-mercado-da-bola",
    "name": "Mercado da Bola",
    "slug": "mercado-da-bola",
    "description": "Cobertura de Mercado da Bola em Bola de Domingo"
  },
  {
    "id": "cat-bastidores",
    "name": "Bastidores",
    "slug": "bastidores",
    "description": "Cobertura de Bastidores em Bola de Domingo"
  }
];

export const breakingHeadlines: BreakingHeadline[] = [
  {
    "id": "brk-1",
    "text": "AO VIVO — Brasileirão: atualização urgente para leitores de Bola de Domingo",
    "slug": "por-que-brasileirao-domina-a-conversa-e-o-que-vem-a-seguir-g4",
    "urgent": true
  },
  {
    "id": "brk-2",
    "text": "AO VIVO — Copa do Brasil: atualização urgente para leitores de Bola de Domingo",
    "slug": "bola-de-domingo-explica-o-ponto-chave-de-brasileirao-nesta-semana-g5",
    "urgent": false
  },
  {
    "id": "brk-3",
    "text": "AO VIVO — Libertadores: atualização urgente para leitores de Bola de Domingo",
    "slug": "brasileirao-o-que-muda-agora-e-o-impacto-direto-para-o-publico-de-bola-d-g6",
    "urgent": false
  }
];

export const articles: Article[] = [
  {
    "id": "art-1",
    "slug": "por-que-brasileirao-domina-a-conversa-e-o-que-vem-a-seguir-g4",
    "title": "Por que Brasileirão domina a conversa — e o que vem a seguir",
    "excerpt": "O que já está confirmado, o que ainda é especulação e o que acompanhar nas próximas horas.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Bola de Domingo</strong> na seção <em>Brasileirão</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "Brasileirão",
    "categorySlug": "brasileirao",
    "author": "Elena Prado",
    "publishedAt": "2026-09-27T00:59:17.534Z",
    "imageUrl": "https://images.unsplash.com/photo-1486286701208-1d58e9338013?w=800&q=80",
    "readCount": 31780,
    "featured": true,
    "isVideo": true,
    "keyPoints": [
      "O que aconteceu em Brasileirão e por que importa para leitores de Bola de Domingo.",
      "Quem são os principais atores e o que cada um defende.",
      "Números e fatos já confirmados até o momento.",
      "Próximos passos e o que acompanhar nas próximas horas.",
      "Contexto rápido para quem chegou agora na cobertura (seed 70)."
    ]
  },
  {
    "id": "art-2",
    "slug": "bola-de-domingo-explica-o-ponto-chave-de-brasileirao-nesta-semana-g5",
    "title": "Bola de Domingo explica: o ponto-chave de Brasileirão nesta semana",
    "excerpt": "Leitura direta para quem acompanha Brasileirão no celular — sem enrolação.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Bola de Domingo</strong> na seção <em>Brasileirão</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "Brasileirão",
    "categorySlug": "brasileirao",
    "author": "Felipe Nunes",
    "publishedAt": "2026-09-26T17:59:17.534Z",
    "imageUrl": "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800&q=80",
    "readCount": 32777,
    "featured": true,
    "isVideo": false,
    "keyPoints": [
      "O que aconteceu em Brasileirão e por que importa para leitores de Bola de Domingo.",
      "Quem são os principais atores e o que cada um defende.",
      "Números e fatos já confirmados até o momento.",
      "Próximos passos e o que acompanhar nas próximas horas.",
      "Contexto rápido para quem chegou agora na cobertura (seed 71)."
    ]
  },
  {
    "id": "art-3",
    "slug": "brasileirao-o-que-muda-agora-e-o-impacto-direto-para-o-publico-de-bola-d-g6",
    "title": "Brasileirão: o que muda agora e o impacto direto para o público de Bola de Domingo",
    "excerpt": "Cobertura rápida e objetiva sobre Brasileirão, com contexto e próximos capítulos.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Bola de Domingo</strong> na seção <em>Brasileirão</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "Brasileirão",
    "categorySlug": "brasileirao",
    "author": "Gabriela Lopes",
    "publishedAt": "2026-09-26T10:59:17.534Z",
    "imageUrl": "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=800&q=80",
    "readCount": 33774,
    "featured": false,
    "isVideo": false,
    "keyPoints": [
      "O que aconteceu em Brasileirão e por que importa para leitores de Bola de Domingo.",
      "Quem são os principais atores e o que cada um defende.",
      "Números e fatos já confirmados até o momento.",
      "Próximos passos e o que acompanhar nas próximas horas.",
      "Contexto rápido para quem chegou agora na cobertura (seed 72)."
    ]
  },
  {
    "id": "art-4",
    "slug": "bastidores-de-copa-do-brasil-analise-com-numeros-e-contexto-g7",
    "title": "Bastidores de Copa do Brasil — análise com números e contexto",
    "excerpt": "O que já está confirmado, o que ainda é especulação e o que acompanhar nas próximas horas.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Bola de Domingo</strong> na seção <em>Copa do Brasil</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "Copa do Brasil",
    "categorySlug": "copa-do-brasil",
    "author": "Hugo Almeida",
    "publishedAt": "2026-09-26T03:59:17.534Z",
    "imageUrl": "https://images.unsplash.com/photo-1517466787929-bc90951d0974?w=800&q=80",
    "readCount": 34771,
    "featured": false,
    "isVideo": false,
    "keyPoints": [
      "O que aconteceu em Copa do Brasil e por que importa para leitores de Bola de Domingo.",
      "Quem são os principais atores e o que cada um defende.",
      "Números e fatos já confirmados até o momento.",
      "Próximos passos e o que acompanhar nas próximas horas.",
      "Contexto rápido para quem chegou agora na cobertura (seed 73)."
    ]
  },
  {
    "id": "art-5",
    "slug": "ultima-hora-em-copa-do-brasil-decisoes-que-mexem-com-a-rodada-g8",
    "title": "Última hora em Copa do Brasil: decisões que mexem com a rodada",
    "excerpt": "Leitura direta para quem acompanha Copa do Brasil no celular — sem enrolação.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Bola de Domingo</strong> na seção <em>Copa do Brasil</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "Copa do Brasil",
    "categorySlug": "copa-do-brasil",
    "author": "Ana Ribeiro",
    "publishedAt": "2026-09-25T20:59:17.534Z",
    "imageUrl": "https://images.unsplash.com/photo-1574629810360-7abcae5a4a2a?w=800&q=80",
    "readCount": 35768,
    "featured": false,
    "isVideo": false,
    "keyPoints": [
      "O que aconteceu em Copa do Brasil e por que importa para leitores de Bola de Domingo.",
      "Quem são os principais atores e o que cada um defende.",
      "Números e fatos já confirmados até o momento.",
      "Próximos passos e o que acompanhar nas próximas horas.",
      "Contexto rápido para quem chegou agora na cobertura (seed 74)."
    ]
  },
  {
    "id": "art-6",
    "slug": "copa-do-brasil-em-foco-tres-leituras-que-importam-hoje-g9",
    "title": "Copa do Brasil em foco: três leituras que importam hoje",
    "excerpt": "Cobertura rápida e objetiva sobre Copa do Brasil, com contexto e próximos capítulos.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Bola de Domingo</strong> na seção <em>Copa do Brasil</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "Copa do Brasil",
    "categorySlug": "copa-do-brasil",
    "author": "Bruno Costa",
    "publishedAt": "2026-09-25T13:59:17.534Z",
    "imageUrl": "https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=800&q=80",
    "readCount": 36765,
    "featured": false,
    "isVideo": false,
    "keyPoints": [
      "O que aconteceu em Copa do Brasil e por que importa para leitores de Bola de Domingo.",
      "Quem são os principais atores e o que cada um defende.",
      "Números e fatos já confirmados até o momento.",
      "Próximos passos e o que acompanhar nas próximas horas.",
      "Contexto rápido para quem chegou agora na cobertura (seed 75)."
    ]
  },
  {
    "id": "art-7",
    "slug": "por-que-libertadores-domina-a-conversa-e-o-que-vem-a-seguir-ga",
    "title": "Por que Libertadores domina a conversa — e o que vem a seguir",
    "excerpt": "O que já está confirmado, o que ainda é especulação e o que acompanhar nas próximas horas.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Bola de Domingo</strong> na seção <em>Libertadores</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "Libertadores",
    "categorySlug": "libertadores",
    "author": "Camila Souza",
    "publishedAt": "2026-09-25T06:59:17.534Z",
    "imageUrl": "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=800&q=80",
    "readCount": 37762,
    "featured": false,
    "isVideo": false,
    "keyPoints": [
      "O que aconteceu em Libertadores e por que importa para leitores de Bola de Domingo.",
      "Quem são os principais atores e o que cada um defende.",
      "Números e fatos já confirmados até o momento.",
      "Próximos passos e o que acompanhar nas próximas horas.",
      "Contexto rápido para quem chegou agora na cobertura (seed 76)."
    ]
  },
  {
    "id": "art-8",
    "slug": "bola-de-domingo-explica-o-ponto-chave-de-libertadores-nesta-semana-gb",
    "title": "Bola de Domingo explica: o ponto-chave de Libertadores nesta semana",
    "excerpt": "Leitura direta para quem acompanha Libertadores no celular — sem enrolação.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Bola de Domingo</strong> na seção <em>Libertadores</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "Libertadores",
    "categorySlug": "libertadores",
    "author": "Diego Martins",
    "publishedAt": "2026-09-27T23:59:17.534Z",
    "imageUrl": "https://images.unsplash.com/photo-1461896836934-ffe607ba6851?w=800&q=80",
    "readCount": 38759,
    "featured": false,
    "isVideo": true,
    "keyPoints": [
      "O que aconteceu em Libertadores e por que importa para leitores de Bola de Domingo.",
      "Quem são os principais atores e o que cada um defende.",
      "Números e fatos já confirmados até o momento.",
      "Próximos passos e o que acompanhar nas próximas horas.",
      "Contexto rápido para quem chegou agora na cobertura (seed 77)."
    ]
  },
  {
    "id": "art-9",
    "slug": "libertadores-o-que-muda-agora-e-o-impacto-direto-para-o-publico-de-bola--gc",
    "title": "Libertadores: o que muda agora e o impacto direto para o público de Bola de Domingo",
    "excerpt": "Cobertura rápida e objetiva sobre Libertadores, com contexto e próximos capítulos.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Bola de Domingo</strong> na seção <em>Libertadores</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "Libertadores",
    "categorySlug": "libertadores",
    "author": "Elena Prado",
    "publishedAt": "2026-09-27T16:59:17.534Z",
    "imageUrl": "https://images.unsplash.com/photo-1486286701208-1d58e9338013?w=800&q=80",
    "readCount": 39756,
    "featured": false,
    "isVideo": false,
    "keyPoints": [
      "O que aconteceu em Libertadores e por que importa para leitores de Bola de Domingo.",
      "Quem são os principais atores e o que cada um defende.",
      "Números e fatos já confirmados até o momento.",
      "Próximos passos e o que acompanhar nas próximas horas.",
      "Contexto rápido para quem chegou agora na cobertura (seed 78)."
    ]
  },
  {
    "id": "art-10",
    "slug": "bastidores-de-selecao-analise-com-numeros-e-contexto-gd",
    "title": "Bastidores de Seleção — análise com números e contexto",
    "excerpt": "O que já está confirmado, o que ainda é especulação e o que acompanhar nas próximas horas.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Bola de Domingo</strong> na seção <em>Seleção</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "Seleção",
    "categorySlug": "selecao",
    "author": "Felipe Nunes",
    "publishedAt": "2026-09-27T09:59:17.534Z",
    "imageUrl": "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800&q=80",
    "readCount": 40753,
    "featured": false,
    "isVideo": false
  },
  {
    "id": "art-11",
    "slug": "ultima-hora-em-selecao-decisoes-que-mexem-com-a-rodada-ge",
    "title": "Última hora em Seleção: decisões que mexem com a rodada",
    "excerpt": "Leitura direta para quem acompanha Seleção no celular — sem enrolação.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Bola de Domingo</strong> na seção <em>Seleção</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "Seleção",
    "categorySlug": "selecao",
    "author": "Gabriela Lopes",
    "publishedAt": "2026-09-27T02:59:17.534Z",
    "imageUrl": "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=800&q=80",
    "readCount": 41750,
    "featured": false,
    "isVideo": false,
    "keyPoints": [
      "O que aconteceu em Seleção e por que importa para leitores de Bola de Domingo.",
      "Quem são os principais atores e o que cada um defende.",
      "Números e fatos já confirmados até o momento.",
      "Próximos passos e o que acompanhar nas próximas horas.",
      "Contexto rápido para quem chegou agora na cobertura (seed 80)."
    ]
  },
  {
    "id": "art-12",
    "slug": "selecao-em-foco-tres-leituras-que-importam-hoje-gf",
    "title": "Seleção em foco: três leituras que importam hoje",
    "excerpt": "Cobertura rápida e objetiva sobre Seleção, com contexto e próximos capítulos.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Bola de Domingo</strong> na seção <em>Seleção</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "Seleção",
    "categorySlug": "selecao",
    "author": "Hugo Almeida",
    "publishedAt": "2026-09-26T19:59:17.534Z",
    "imageUrl": "https://images.unsplash.com/photo-1517466787929-bc90951d0974?w=800&q=80",
    "readCount": 42747,
    "featured": false,
    "isVideo": false
  },
  {
    "id": "art-13",
    "slug": "por-que-mercado-da-bola-domina-a-conversa-e-o-que-vem-a-seguir-gg",
    "title": "Por que Mercado da Bola domina a conversa — e o que vem a seguir",
    "excerpt": "O que já está confirmado, o que ainda é especulação e o que acompanhar nas próximas horas.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Bola de Domingo</strong> na seção <em>Mercado da Bola</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "Mercado da Bola",
    "categorySlug": "mercado-da-bola",
    "author": "Ana Ribeiro",
    "publishedAt": "2026-09-26T12:59:17.534Z",
    "imageUrl": "https://images.unsplash.com/photo-1574629810360-7abcae5a4a2a?w=800&q=80",
    "readCount": 43744,
    "featured": false,
    "isVideo": false,
    "keyPoints": [
      "O que aconteceu em Mercado da Bola e por que importa para leitores de Bola de Domingo.",
      "Quem são os principais atores e o que cada um defende.",
      "Números e fatos já confirmados até o momento.",
      "Próximos passos e o que acompanhar nas próximas horas.",
      "Contexto rápido para quem chegou agora na cobertura (seed 82)."
    ]
  },
  {
    "id": "art-14",
    "slug": "bola-de-domingo-explica-o-ponto-chave-de-mercado-da-bola-nesta-semana-gh",
    "title": "Bola de Domingo explica: o ponto-chave de Mercado da Bola nesta semana",
    "excerpt": "Leitura direta para quem acompanha Mercado da Bola no celular — sem enrolação.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Bola de Domingo</strong> na seção <em>Mercado da Bola</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "Mercado da Bola",
    "categorySlug": "mercado-da-bola",
    "author": "Bruno Costa",
    "publishedAt": "2026-09-26T05:59:17.534Z",
    "imageUrl": "https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=800&q=80",
    "readCount": 44741,
    "featured": false,
    "isVideo": false
  },
  {
    "id": "art-15",
    "slug": "mercado-da-bola-o-que-muda-agora-e-o-impacto-direto-para-o-publico-de-bo-gi",
    "title": "Mercado da Bola: o que muda agora e o impacto direto para o público de Bola de Domingo",
    "excerpt": "Cobertura rápida e objetiva sobre Mercado da Bola, com contexto e próximos capítulos.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Bola de Domingo</strong> na seção <em>Mercado da Bola</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "Mercado da Bola",
    "categorySlug": "mercado-da-bola",
    "author": "Camila Souza",
    "publishedAt": "2026-09-25T22:59:17.534Z",
    "imageUrl": "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=800&q=80",
    "readCount": 45738,
    "featured": false,
    "isVideo": true,
    "keyPoints": [
      "O que aconteceu em Mercado da Bola e por que importa para leitores de Bola de Domingo.",
      "Quem são os principais atores e o que cada um defende.",
      "Números e fatos já confirmados até o momento.",
      "Próximos passos e o que acompanhar nas próximas horas.",
      "Contexto rápido para quem chegou agora na cobertura (seed 84)."
    ]
  },
  {
    "id": "art-16",
    "slug": "bastidores-de-bastidores-analise-com-numeros-e-contexto-gj",
    "title": "Bastidores de Bastidores — análise com números e contexto",
    "excerpt": "O que já está confirmado, o que ainda é especulação e o que acompanhar nas próximas horas.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Bola de Domingo</strong> na seção <em>Bastidores</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "Bastidores",
    "categorySlug": "bastidores",
    "author": "Diego Martins",
    "publishedAt": "2026-09-25T15:59:17.534Z",
    "imageUrl": "https://images.unsplash.com/photo-1461896836934-ffe607ba6851?w=800&q=80",
    "readCount": 46735,
    "featured": false,
    "isVideo": false
  },
  {
    "id": "art-17",
    "slug": "ultima-hora-em-bastidores-decisoes-que-mexem-com-a-rodada-gk",
    "title": "Última hora em Bastidores: decisões que mexem com a rodada",
    "excerpt": "Leitura direta para quem acompanha Bastidores no celular — sem enrolação.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Bola de Domingo</strong> na seção <em>Bastidores</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "Bastidores",
    "categorySlug": "bastidores",
    "author": "Elena Prado",
    "publishedAt": "2026-09-25T08:59:17.534Z",
    "imageUrl": "https://images.unsplash.com/photo-1486286701208-1d58e9338013?w=800&q=80",
    "readCount": 47732,
    "featured": false,
    "isVideo": false,
    "keyPoints": [
      "O que aconteceu em Bastidores e por que importa para leitores de Bola de Domingo.",
      "Quem são os principais atores e o que cada um defende.",
      "Números e fatos já confirmados até o momento.",
      "Próximos passos e o que acompanhar nas próximas horas.",
      "Contexto rápido para quem chegou agora na cobertura (seed 86)."
    ]
  },
  {
    "id": "art-18",
    "slug": "bastidores-em-foco-tres-leituras-que-importam-hoje-gl",
    "title": "Bastidores em foco: três leituras que importam hoje",
    "excerpt": "Cobertura rápida e objetiva sobre Bastidores, com contexto e próximos capítulos.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Bola de Domingo</strong> na seção <em>Bastidores</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "Bastidores",
    "categorySlug": "bastidores",
    "author": "Felipe Nunes",
    "publishedAt": "2026-09-28T01:59:17.534Z",
    "imageUrl": "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800&q=80",
    "readCount": 48729,
    "featured": false,
    "isVideo": false
  }
];

export const alerts: AlertItem[] = [
  {
    "id": "alert-1",
    "level": "Urgente",
    "title": "Atualização crítica em Brasileirão — acompanhe minuto a minuto",
    "href": "/artigo/por-que-brasileirao-domina-a-conversa-e-o-que-vem-a-seguir-g4",
    "publishedAt": "2026-09-27T00:59:17.534Z"
  },
  {
    "id": "alert-2",
    "level": "Importante",
    "title": "Bola de Domingo: comunicado oficial sobre cobertura em tempo real",
    "href": "/alertas",
    "publishedAt": "2026-09-26T17:59:17.534Z"
  },
  {
    "id": "alert-3",
    "level": "Aviso",
    "title": "Manutenção programada da área de alertas (demo)",
    "publishedAt": "2026-09-26T10:59:17.534Z"
  },
  {
    "id": "alert-4",
    "level": "Urgente",
    "title": "Desenvolvimento em Copa do Brasil com impacto nacional",
    "href": "/artigo/bola-de-domingo-explica-o-ponto-chave-de-brasileirao-nesta-semana-g5",
    "publishedAt": "2026-09-26T03:59:17.534Z"
  },
  {
    "id": "alert-5",
    "level": "Importante",
    "title": "Fontes oficiais confirmam novo capítulo da história em acompanhamento",
    "publishedAt": "2026-09-25T20:59:17.534Z"
  },
  {
    "id": "alert-6",
    "level": "Aviso",
    "title": "Lembrete editorial: confira a política de atualização ao vivo",
    "href": "/sobre",
    "publishedAt": "2026-09-25T13:59:17.534Z"
  }
];

export const liveStories: LiveStory[] = [
  {
    "id": "live-1",
    "slug": "demo-nacional",
    "title": "AO VIVO — Cobertura nacional de Bola de Domingo",
    "summary": "Linha do tempo demonstrativa com fontes rotuladas e âncoras estáveis.",
    "updatedAt": "2026-09-27T00:59:17.534Z",
    "updates": [
      {
        "id": "upd-1",
        "at": "2026-09-27T00:59:17.534Z",
        "source": "Redação",
        "text": "Início da cobertura ao vivo. Equipe monitora fontes oficiais e correspondentes."
      },
      {
        "id": "upd-2",
        "at": "2026-09-26T17:59:17.534Z",
        "source": "Agência",
        "text": "Primeira confirmação independente chega à mesa. Texto em verificação cruzada."
      },
      {
        "id": "upd-3",
        "at": "2026-09-26T10:59:17.534Z",
        "source": "Correspondente",
        "text": "Cena local descrita com cautela — sem especulação além do observado."
      },
      {
        "id": "upd-4",
        "at": "2026-09-26T03:59:17.534Z",
        "source": "Redação",
        "text": "Linha do tempo reorganizada. Âncoras de atualização permanecem estáveis."
      },
      {
        "id": "upd-5",
        "at": "2026-09-25T20:59:17.534Z",
        "source": "Especialista",
        "text": "Contexto rápido para leitores que acabaram de entrar na cobertura."
      },
      {
        "id": "upd-6",
        "at": "2026-09-25T13:59:17.534Z",
        "source": "Redação",
        "text": "Última atualização desta demonstração. Em produção, o CMS alimenta este feed."
      }
    ]
  },
  {
    "id": "live-2",
    "slug": "demo-regional",
    "title": "AO VIVO — Frente regional (br-bahia)",
    "summary": "Segundo demo de live-blog para validar rotas e UI.",
    "updatedAt": "2026-09-26T10:59:17.534Z",
    "updates": [
      {
        "id": "upd-r1",
        "at": "2026-09-26T10:59:17.534Z",
        "source": "Redação regional",
        "text": "Abertura do blog regional com foco em impacto local."
      },
      {
        "id": "upd-r2",
        "at": "2026-09-26T03:59:17.534Z",
        "source": "Prefeitura / órgão local (demo)",
        "text": "Nota oficial demonstrativa — rotular fonte é obrigatório neste layout."
      }
    ]
  }
];
